
tasks:
  - name: Setup Rocker Containers
    init: |
      docker-compose pull
      make rocker-distill
  - name: Install Nextflow
    init: curl -s https://get.nextflow.io | bash
    command: sudo mv nextflow /usr/local/bin

ports:
  # Expose port for RStudio
  - port: 8787
    onOpen: open-browser

vscode:
  extensions:
    - ritwickdey.liveserver