# Run using: docker compose up
version: "3.9"
services:
  rstudio:
    image: 'rocker/verse:4.1.1'
    ports:
      - 127.0.0.1:8787:8787
    environment:
      - 'DISABLE_AUTH=true'
    volumes:
      - "$PWD:/home/rstudio"
    working_dir: /home/rstudio
    # user: "$UID:$GROUPS"
