illumina_fastq:
  - '/workspace/data/raw/SRR2589044_{1,2}.fastq.gz'
  - '/workspace/data/raw/SRR2584863_{1,2}.fastq.gz'
  - '/workspace/data/raw/SRR2584866_{1,2}.fastq.gz'
reference: 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/017/985/GCA_000017985.1_ASM1798v1/GCA_000017985.1_ASM1798v1_genomic.fna.gz'
outdir: '/workspace/data/results'